apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets 
          image: djedjethai/tickets
          env:
          - name: NATS_CLIENT_ID 
            valueFrom: # get the name of the pod
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing # quotes ??
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-srv:27017/tickets'
          - name: JWT_KEY
            valueFrom: 
              secretKeyRef:
                name: secrets
                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000  


        # apiVersion: apps/v1
        # kind: Deployment
        # metadata:
        #   name: auth-depl 
        # spec: 
        #   replicas: 1
        #   selector:
        #     matchLabels:
        #       app: auth
        #   template:
        #     metadata:
        #       labels:
        #         app: auth
        #     spec:
        #       containers:
        #         - name: auth 
        #           image: us.gcr.io/ticketing-dev-305610/auth
        # ---
        # apiVersion: v1
        # kind: Service
        # metadata:
        #   name: auth-srv
        # spec:
        #   selector:
        #     app: auth
        #   ports:
        #     - name: auth
        #       protocol: TCP
        #       port: 3000
        #       targetPort: 3000  


